# Webpage
title: Anthony Burrow
description: >-
  Anthony Burrow's personal webpage.

url: "https://anthonyburrow.github.io"
baseurl: ""

theme: jekyll-theme-chirpy

tagline: Graduate Research Assistant
avatar: assets/img/avatar.jpg

# Settings
collections:
  tabs:
    output: true
    sort_by: order
    permalink: /:title/
  projects:
    output: true
    permalink: /projects/:title/

defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: "_projects"
    values:
      layout: project
      permalink: /projects/:title/
      pinned: False
